core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("vehicles.urls")),
    path("", include("pages.urls")),
    path("accounts/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path('about-us/', views.about_us, name='about_us'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import get_profile

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path("profile/", get_profile, name="profile"),
]

vehicles/urls.py
from django.urls import path

from .views import get_vehicle_list, get_vehicle_details

urlpatterns = [
    path("", get_vehicle_list, name="vehicle_list"),
    path("<int:pk>/", get_vehicle_details, name="vehicle_detail"),
]

blog/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

vehicles/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class Make(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class VehicleModel(models.Model):
    name = models.CharField(max_length=128)
    make = models.ForeignKey(Make, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Vehicle(models.Model):
    class TransmissionType(models.TextChoices):
        Automatic = "automatic", _("Automatic")
        Manual = "manual", _("Manual")

    title = models.CharField(_("title"), max_length=256)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    year = models.IntegerField(_("year"))
    transmission = models.CharField(max_length=16, choices=TransmissionType.choices)
    km = models.IntegerField(blank=True, null=True)
    color = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    make = models.ForeignKey(Make, null=True, on_delete=models.SET_NULL)
    vehicle_model = models.ForeignKey(VehicleModel, null=True, on_delete=models.SET_NULL)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    published_on = models.DateTimeField()

    def __str__(self):
        return self.title


class Picture(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="pictures")


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=32)
    address = models.CharField(max_length=128)
    city = models.CharField(max_length=64)
    country = models.CharField(max_length=64)
    zip_code = models.CharField(max_length=16)
    picture = models.ImageField(upload_to="profile_pictures", blank=True, null=True)
    bio = models.TextField(blank=True)

    def __str__(self):
        return self.user.get_full_name()

pages/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(label="Name", required=True, max_length=128)
    email = forms.EmailField(label="Email", required=True)
    subject = forms.CharField(label="Subject", max_length=256)
    message = forms.CharField(label="Message", required=True, widget=forms.Textarea)

blog/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect

from .forms import ContactForm


def about_us(request):
    return render(request, "pages/about_us.html")


def contact_us(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            subject = form.cleaned_data.get("subject", "Greetings from your website!")
            message = form.cleaned_data["message"]

            send_mail(
                subject,
                f"FROM: {name}\n{message}",
                email,
                settings.ADMINS,
                fail_silently=False,
                html_message=f"<div><p><em>From:</em> {name}</p><p>{message}</p></div>",
            )
            return redirect("pages:contact_us")
    else:
        form = ContactForm()
    return render(request, "pages/contact_us.html", context={"form": form})


def privacy_policy(request):
    return render(request, "pages/privacy_policy.html")


def terms_of_service(request):
    return render(request, "pages/terms_of_service.html")

users/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def get_profile(request):
    return render(request, "users/profile.html")

vehicles/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse

from .models import Vehicle


def get_vehicle_list(request: HttpRequest) -> HttpResponse:
    vehicles = Vehicle.objects.order_by('-published_on').all()

    return render(request, "vehicles/vehicle_list.html", {
        "vehicles": vehicles
    })


def get_vehicle_details(request: HttpRequest, pk: int) -> HttpResponse:
    vehicle = get_object_or_404(Vehicle.objects.select_related('make', 'vehicle_model'), pk=pk)
    return render(request, "vehicles/vehicle_detail.html", {
        "vehicle": vehicle,
    })

pages/templates/pages/about_us.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% translate "About Us" %} - {{ block.super }}{% endblock title %}

{% block content %}
<h1>About us</h1>
{% endblock content %}

pages/templates/pages/contact_us.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load i18n %}

{% block title %}{% translate "Contact us" %} - {{ block.super }}{% endblock title %}

{% block content %}
<h1>{% translate "Contact us" %}</h1>
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">{% translate "Send message" %}</button>
</form>
{% endblock content %}

pages/templates/pages/privacy_policy.html
{% extends "base.html" %}

{% block title %}Privacy Policy - {{ block.super }}{% endblock title %}

{% block content %}
<h1>Privacy Policy</h1>
<p>Privacy policy goes here.</p>
<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Distinctio consequuntur earum eos quisquam iusto delectus, esse quo a animi eum veniam non, aut iure sapiente qui accusamus. Nam, veniam sequi!</p>
{% endblock content %}

pages/templates/pages/terms_of_service.html
{% extends "base.html" %}

{% block title %}Terms and Conditions - {{ block.super }}{% endblock title %}

{% block content %}
<h1>Terms and Conditions</h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam ullam beatae, ipsa pariatur dolores quis corrupti dolorem necessitatibus ipsam amet nesciunt accusantium cumque velit incidunt, reiciendis eum inventore? Soluta, fuga.</p>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur perspiciatis maxime qui saepe, odit modi earum fugiat, molestias nostrum quo ab minus quis provident magni ipsam officia obcaecati quibusdam nisi!</p>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, laborum provident accusamus rerum veritatis aperiam quaerat corrupti deleniti tempora libero eaque et doloremque cupiditate autem accusantium nobis nihil nesciunt fugiat.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius explicabo sit dignissimos repellat nulla blanditiis magni distinctio consequuntur delectus velit aperiam numquam enim error eveniet esse in deleniti, sapiente nemo!</p>
{% endblock content %}

templates/base.html
<!doctype html>{% load static %}
<html lang="en" class="h-100" data-bs-theme="auto">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Ndryshe nga merrjep nuk ju rrjep">
    <meta name="author" content="Gledi">
    <title>{% block title %}sterrjep.al{% endblock title %}</title>
    {% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    {% endblock styles %}
  </head>
  <body class="d-flex flex-column h-100">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'vehicle_list' %}">sterrjep<span>.al</span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'vehicle_list' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:about_us' %}">About Us</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'pages:privacy_policy' %}" class="nav-link">Privacy Policy</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'pages:terms_of_service' %}" class="nav-link">Terms & Conditions</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'pages:contact_us' %}" class="nav-link">Contact Us</a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link">Blog</a>
              </li>
            </ul>
            <ul class="navbar-nav">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'profile' %}" class="nav-link">Welcome <strong>{{ user }}</strong></a>
              </li>
              <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a href="{% url 'login' %}" class="nav-link">Login</a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link">Register</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="flex-shrink-0">
      <div class="container">
        {% block content %}{% endblock content %}
      </div>
    </main>
    <footer class="footer mt-auto py-3 bg-body-tertiary">
      <div class="container">
        <span class="text-body-secondary">Copyright &copy; 2023 &mdash; sterrjep.al</span>
      </div>
    </footer>
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    {% endblock scripts %}
  </body>
</html>

users/templates/users/logged_out.html
{% extends "base.html" %}

users/templates/users/login.html
{% extends "base.html" %}

{% block title %}Sign In - {{ block.super }}{% endblock title %}

{% block content %}
<h1>Sign in</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button type="submit" class="btn btn-primary">Sign In</button>
</form>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block title %}{{ user }} - Profile - {{ block.super }}{% endblock title %}

{% block content %}
<h1>User Profile</h1>
<div>
    <img src="{{ user.profile.picture.url }}" alt="{{ user.get_full_name }}">
</div>
<p>Name: {{ user.get_full_name }}</p>
<p>Tel: {{ user.profile.phone_number }}</p>
<address>
    Address:<br>
    {{ user.profile.address }}<br>
    {{ user.profile.city }}<br>
    {{ user.profile.country }}<br>
    {{ user.profile.zip_code }}
</address>
{% endblock content %}

vehicles/templates/vehicles/vehicle_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="row">
  <div class="col-9">
    <p>{% translate "Published on" %}: {{ vehicle.published_on|date:"l, M jS Y" }}</p>
    <div id="carouselExampleIndicators" class="carousel slide">
      <div class="carousel-indicators">
        {% for pic in vehicle.picture_set.all %}
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active" aria-current="true"{% endif %} aria-label="Slide {{ forloop.counter }}"></button>
        {% endfor %}
      </div>
      <div class="carousel-inner">
        {% for pic in vehicle.picture_set.all %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
          <img src="{{ pic.photo.url }}" class="d-block w-100" alt="{{ pic.photo.name }}">
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <h2>{{ vehicle.title }}</h2>
    <h3>{{ vehicle.price|floatformat:"-3g" }} EUR</h3>
    <div>
      <span class="badge bg-secondary">Year: {{ vehicle.year }}</span>
      <span class="badge bg-secondary">KM: {{ vehicle.km }}</span>
      <span class="badge bg-secondary">Transmission: {{ vehicle.get_transmission_display }}</span>
      <span class="badge bg-secondary">Color: {{ vehicle.color }}</span>
      <span class="badge bg-secondary">Make: {{ vehicle.make.name }}</span>
      <span class="badge bg-secondary">Model: {{ vehicle.vehicle_model.name }}</span>
    </div>
    <div>
      {{ vehicle.description|linebreaks }}
    </div>
  </div>
  <div class="col-3">
    <h4>Shitesi</h4>
    <p class="fs-3">{{ vehicle.author.get_full_name }}</p>
    <figure>
      <img src="{{ vehicle.author.profile.picture.url }}" alt="{{ vehicle.author.get_full_name }}">
    </figure>
    <div class="alert alert-primary" role="alert">
      Tel: <strong>{{ vehicle.author.profile.phone_number }}</strong>
    </div>
    <h5>Address:</h5>
    <address>
      {{ vehicle.author.profile.address }}<br>
      {{ vehicle.author.profile.city }}<br>
      {{ vehicle.author.profile.country }}<br>
      {{ vehicle.author.profile.zip_code }}
    </address>
  </div>
</div>

{% endblock content %}

vehicles/templates/vehicles/vehicle_list.html
{% extends "base.html" %}

{% block content %}
<h1>Vehicles</h1>
{% for vehicle in vehicles %}
<p>
    <a href="{% url 'vehicle_detail' pk=vehicle.pk %}">{{ vehicle.title }}</a>
</p>
{% empty %}
<p>No vehicles added yet!!!</p>
{% endfor %}
{% endblock content %}